### PR TITLE
Fixes #18

### LINKED ISSUE #18: To group tabs on the basis of their functionality/content

### PR DESCRIPTION
**Pull request by kunalmnnit**

### CODE REVIEW

**Comment by akshay31057** [comment]
@kunalmnnit There is some error in your code. The extension is not working properly.

**Comment by kunalmnnit** [comment]
Sir,please provide description of error being faced

**Comment by akshay31057** [comment]
@kunalmnnit the voice and speech part is not working actually. Can you mail the working code to akshay31057@gmail.com if it is working fine for you or share the repo link?

**Comment by hiiiideepak** [comment]
> @kunalmnnit the voice and speech part is not working actually. Can you mail the working code to [akshay31057@gmail.com](mailto:akshay31057@gmail.com) if it is working fine for you or share the repo link?

no response from @kunalmnnit , closing this pr and partial points will be awarded.

**Pull request closed without merging**
